/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficas;

import MisClases.Plaza;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author omar
 */
public class Pnt_Captura_Plaza extends javax.swing.JInternalFrame {

    ArrayList<Plaza> datos = null;
    
    public void setDatos(ArrayList<Plaza> datos) {
        this.datos = datos;
    }
    /**
     * Creates new form Pnt_Captura_Comandante
     */
    public Pnt_Captura_Plaza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_pla = new javax.swing.JTextField();
        txt_nom = new javax.swing.JTextField();
        txt_cid = new javax.swing.JTextField();
        txt_pol = new javax.swing.JTextField();
        txt_pob = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();

        setClosable(true);
        setTitle("Registro de Comandantes");

        jLabel2.setText("Número de Plaza:");

        jLabel3.setText("Nombre (s):");

        jLabel4.setText("Ciudad:");

        jLabel5.setText("Policías:");

        jLabel6.setText("No. Población Civil:");

        txt_pla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_plaActionPerformed(evt);
            }
        });

        txt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomActionPerformed(evt);
            }
        });

        jLabel7.setText("(Max: 15 carácteres)");

        jLabel8.setText("(Max: 15 carácteres)");

        jLabel9.setText("(Max: 15 carácteres)");

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("¡ÚNICO!");

        jLabel1.setText("Ingrese un número entero");

        btn_save.setText("Guardar");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_pol, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(txt_cid, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nom, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_pla, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_pob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_pla)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nom)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_cid)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_pol)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_pob)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_plaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_plaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_plaActionPerformed

    private void txt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        try {
            int flag = 0;
            
            String IdPlaza = txt_pla.getText();
            if(IdPlaza.length() > 15) {
                JOptionPane.showMessageDialog(null, "El nombre excede los 15 carácteres");
                flag += 1;
            }
            if(IdPlaza.length() < 1) {
                JOptionPane.showMessageDialog(null, "._. mínimo escribe algo");
                flag += 1;
            }
            String Nombre = txt_nom.getText();
            if(Nombre.length() > 15) {
                JOptionPane.showMessageDialog(null, "El nombre excede los 15 carácteres");
                flag += 1;
            }
            if(Nombre.length() < 1) {
                JOptionPane.showMessageDialog(null, "._. mínimo escribe algo");
                flag += 1;
            }
            String Ciudad = txt_cid.getText();
            if(Ciudad.length() > 15) {
                JOptionPane.showMessageDialog(null, "El nombre excede los 15 carácteres");
                flag += 1;
            }
            if(Ciudad.length() < 1) {
                JOptionPane.showMessageDialog(null, "._. mínimo escribe algo");
                flag += 1;
            }
        Integer Policias = Integer.valueOf(txt_pol.getText());
        Integer NPC = Integer.valueOf(txt_pob.getText());

        if(flag != 0) {
            JOptionPane.showMessageDialog(null, "Procure no equivocarse");
            txt_pla.setText("");
            txt_nom.setText("");
            txt_cid.setText("");
            txt_pol.setText("");
            txt_pob.setText("");
        }
        
        Plaza p = new Plaza(IdPlaza);
        p.setNombre(Nombre);
        p.setCiudad(Ciudad);
        p.setPolicias(Policias);
        p.setNPC(NPC);
        
        this.datos.add(p);
        
        txt_pla.setText("");
        txt_nom.setText("");
        txt_cid.setText("");
        txt_pol.setText("");
        txt_pob.setText("");
        } catch(NumberFormatException e ) {
                JOptionPane.showMessageDialog(null, "Dije Números >:V");
        } 
    }//GEN-LAST:event_btn_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_cid;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_pla;
    private javax.swing.JTextField txt_pob;
    private javax.swing.JTextField txt_pol;
    // End of variables declaration//GEN-END:variables
}
